// Code generated by mockery v2.36.1. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// Declarable is an autogenerated mock type for the Declarable type
type Declarable struct {
	mock.Mock
}

// DeclareRoutes provides a mock function with given fields: _a0
func (_m *Declarable) DeclareRoutes(_a0 *echo.Group) {
	_m.Called(_a0)
}

// NewDeclarable creates a new instance of Declarable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeclarable(t interface {
	mock.TestingT
	Cleanup(func())
}) *Declarable {
	mock := &Declarable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
