// Code generated by mockery v2.36.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IdCreator is an autogenerated mock type for the IdCreator type
type IdCreator struct {
	mock.Mock
}

// Create provides a mock function with given fields:
func (_m *IdCreator) Create() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewIdCreator creates a new instance of IdCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdCreator {
	mock := &IdCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
