# Lista de pacotes permitidos para importação em arquivos dentro de internal
# Adicione outros pacotes conforme necessário

[allowed]
pkgs = [
  "fmt",
  "strings",
  "os",
  "io",
  "bytes",
  "time",
  "context",
  "errors",
  "sync",
  "math",
  "sort",
  "net",
  "net/http",
  "encoding/json",
  "path",
  "path/filepath",
  "reflect",
  "strconv",
  "regexp",
  "log",
  "testing",
  "unicode",
  "unicode/utf8",
  "bufio",
  "database/sql",
  "flag",
  "text/template",
  "html/template",
  "crypto/rand",
  "crypto/sha256",
  "crypto/sha512",
  "crypto/hmac",
  "crypto/ecdsa",
  "crypto/elliptic",
  "crypto/x509",
  "crypto/x509/pkix",
  "crypto/tls",
  "crypto",
  "encoding/base64",
  "encoding/hex",
  "encoding/csv",
  "encoding/xml",
  "math/rand",
  "runtime",
  "runtime/debug",
  "syscall",
  "os/exec",
  "os/signal",
  "os/user",
  "embed",
  "compress/gzip",
  "compress/zlib",
  "mime/multipart",
  "mime",
  "container/list",
  "container/ring",
  "hash",
  "hash/crc32",
  "hash/fnv",
  "image",
  "image/color",
  "image/draw",
  "image/gif",
  "image/jpeg",
  "image/png",
  "io/ioutil",
  "math/big",
  "math/cmplx",
  "net/mail",
  "net/smtp",
  "net/textproto",
  "net/url",
  "plugin",
  "runtime/pprof",
  "runtime/trace",
  "sync/atomic",
  "testing/quick",
  "text/scanner",
  "text/tabwriter",
  "text/template/parse",
  "time/tzdata",
  "unicode/utf16",
  "github.com/fatih/structs",
  "github.com/jmoiron/sqlx"
] 