// Code generated by ent, DO NOT EDIT.

package cart

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the cart type in the database.
	Label = "cart"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldModifiedAt holds the string denoting the modifiedat field in the database.
	FieldModifiedAt = "modified_at"
	// Table holds the table name of the cart in the database.
	Table = "carts"
)

// Columns holds all SQL columns for cart fields.
var Columns = []string{
	FieldID,
	FieldModifiedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "carts"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_cart",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Cart queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByModifiedAt orders the results by the ModifiedAt field.
func ByModifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModifiedAt, opts...).ToFunc()
}
